### ISSUE TITLE
[Conteúdo] Texto da página "Como contribuir"

### ISSUE THREAD

**Issue by straube** [phppr/docker-phppr.org#14]
No texto da página "Como contribuir" aparece a seguinte frase:

> Nos sinalize caso tenha intensão de escrever artigos e colocaremos seu usuário como Editor.

Apenas uma pequena correção: **intenção** é com "ç". Como o conteúdo está, provavelmente, na base do Wordpress, não dá para ajustar via pull request.

**Comment by nandomoreirame** [comment]
Obrigado por contribuir @straube.

👍
