### ISSUE TITLE
Erro ao tentar logar com Github.

### ISSUE THREAD

**Issue by emersoncl** [phppr/docker-phppr.org#21]
Ao tentar logar no site phppr.org usando Github, está dando erro no retorno da autenticação. 
Estou usando navegador Firefox 54.0 (64-bit).
Na URL a seguir tem uma descrição do erro http://phppr.org/wp-admin/admin-ajax.php?action=github_oauth_redirect&error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch.

**Comment by nandomoreirame** [comment]
Pode testar novamente @emersoncl? :metal:

**Comment by nandomoreirame** [comment]
Problema que quando instalamos o SSL no servidor não mudamos a config no settings da aplicação aqui no Github :)
