### ISSUE TITLE
Fechar hospedagem

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/docker-phppr.org#3]
Felipe, que já organizou comigo o PHP Day Curitiba, se ofereceu para hospedar.
Confirmar com ele.

**Comment by nandomoreirame** [comment]
Qualquer coisa eu tenho uma revenda, posso hospedar por aqui se precisar.

**Comment by nandomoreirame** [comment]
Hospedagem configurada e apontando para > [phppr.org](http://phppr.org/) 👍
