### ISSUE TITLE
Instalação Wordpress no servidor

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/docker-phppr.org#4]

**Comment by nandomoreirame** [comment]
WordPress 4.7.2 instalado no server [phppr.org](http://phppr.org/) 🤘

**Comment by flaviosilveira** [comment]
O que falta para liberar? Artigos? Conteúdo?
Vale outra issue?

**Comment by nandomoreirame** [comment]
Vale sim, várias outras... vou criar elas pera lá
