### ISSUE TITLE
Discussão pessoal sobre pós wordpress

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/docker-phppr.org#5]

**Comment by nandomoreirame** [comment]
O que é pra discutirmos aqui mesmo?

**Comment by flaviosilveira** [comment]
Acho que é se vamos sair do Wordpress depois e se sim, o que vamos desenvolver.
Tecnologias, estrutura, etc.

**Comment by nandomoreirame** [comment]
Será mesmo que precisaríamos sair do WordPress e refazer o projeto inteiro? Será que ele não supre nossas necessidades e pode ficar por muito mais tempo?

**Comment by flaviosilveira** [comment]
Acredito que sim. Acho que se for para sair é uma discussão bem futura.

**Comment by nandomoreirame** [comment]
Show, vale adicionar um Milestone então?

**Comment by yurivecchi** [comment]
o Wordpress tem a vantagem de ter a parte de publicação com autores convidados e etc, acho que é a ferramenta certa se for para usarmos o site para divulgação de artigos da comunidade.

**Comment by jeanmalves** [comment]
Acho que se for para adicionar funcionalidades bem específicas que o
wordpress não atende é bom pensarmos em sair. Por enquanto acho que está
legal, só manter atualizado e de olho nas vulnerabilidades rss.

2017-02-21 9:43 GMT-03:00 Yuri Vecchi <notifications@github.com>:

**Comment by marioernestoms** [comment]
Na minha opinião digo com propriedade não existe funcionalidade que o WordPress não atenda. Se da pra fazer com PHP da pra fazer no WordPress. Por isso não acho que vale a pena refazer tudo. Sei que cai aqui de pára-quedas, vim do Twitter. E achei legal entrar aqui pra dizer issso. Desculpem a intromissão.

**Comment by nandomoreirame** [comment]
Podemos fechar essa issue pessoal?

**Comment by flaviosilveira** [comment]
Acho que para agora sim.
