### ISSUE TITLE
Renomear o projeto

### ISSUE THREAD

**Issue by nandomoreirame** [phppr/docker-phppr.org#8]
O que vocês acham de renomear o projeto para **phppr.org**?

😄

**Comment by nandomoreirame** [comment]
ou **portal-php-pr** 😄

**Comment by nandomoreirame** [comment]
ou **portal-phppr.org**

**Comment by nandomoreirame** [comment]
Por favor votem com reactions 👍 qual nome seria mais interessante para o repositório.

**"Que os jogos comecem!"**

**Comment by jeanmalves** [comment]
phppr.org 👍

**Comment by freitasmurillo** [comment]
O phppr.org fica mais limpo e claro. Sem Portal fica melhor

**Comment by nandomoreirame** [comment]
Pessoal, renomando o projeto para **phppr.org** 👍

**Comment by nandomoreirame** [comment]
Done.
